### PR TITLE
add C4297

### PR DESCRIPTION
**Pull request by lkotsonis**

### CODE REVIEW

**Comment by lkotsonis** [comment]
> just terminate?

Not sure I undestand what you mean here

**Comment by sunbubble** [comment]
> > just terminate?
> 
> Not sure I understand what you mean here

The warning is about throwing an exception from a function marked `noexcept`

**Review by stephanwidor-holoplot — APPROVED** [review]
just out of interest: which lib we are using is giving that warning?

**Comment by lkotsonis** [comment]
> just out of interest: which lib we are using is giving that warning?

boost process

**Comment by lkotsonis** [comment]
> > > just terminate?
> > 
> > 
> > Not sure I understand what you mean here
> 
> The warning is about throwing an exception from a function marked `noexcept`

alright, is there a point to this comment though? I still don't get it

**Pull request merged**
